### ISSUE TITLE
about image format of hps_models

### ISSUE THREAD

**Issue by akioolin** [google/CFU-Playground#184]
Hi:

right now, I'm trying to add some framebuffer utility functions to help me to show some information on framebuffer via qmtech wukong board's hdmi output.

I met a problem which is about image format of hps_model. 
when I use https://rawpixels.net to check the mnv2's image data, it is RGB24. pixel order is RGB, packed. the image is correct shown very normal.

after apply the same setting on the image of hps_models, there is not shown correctly.
like the following image.

![圖片](https://user-images.githubusercontent.com/32902617/126600858-0c723a10-5fef-4e55-be8a-aefed9bd5140.png)

If i change the rawpixel setting to the following shows. I got the nearest image.

![圖片](https://user-images.githubusercontent.com/32902617/126601079-2af2bd4f-fd7e-4663-ac24-2c10ee01b544.png)

Could some body do me a favor to tell me the right format of hps_model's image ??

BR, Akio

**Comment by alanvgreen** [comment]
Hi Akio,

hps_model's input format is 320x240 8-bit grayscale. Could you please try cat_picture.dat with those settings?

Alan

**Comment by akioolin** [comment]
Hi, Alan:

Many thanks. It is right and this could be a grayscale test image for my current code.
Here is the output.

![圖片](https://user-images.githubusercontent.com/32902617/126723251-855b0852-d281-4634-b58a-c74df8334fa3.png)


BR, Akio

**Comment by alanvgreen** [comment]
Looking good!

**Comment by akioolin** [comment]
Hi, Alan:

the same result is shown on hdmi monitor. 
Many Thanks.

BR, Akio
