### ISSUE TITLE
ERROR: Module `\FD' referenced in module `\digilent_arty' in cell `\FD_7' is not part of the design.

### ISSUE THREAD

**Issue by tcal-x** [google/CFU-Playground#380]
Caught in SymbiFlow CI tests.

This repo may be the only place where latest SymbiFlow is tested with (fairly) current LiteX.

The last successful SymbiFlow CI run in this repo was 2 days ago.

Here we **don't** pin the Conda package versions, so the tests here use the 'latest' packages.

**Comment by tcal-x** [comment]
https://github.com/google/CFU-Playground/runs/4536982520?check_suite_focus=true

**Comment by kgugala** [comment]
this is fixed in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2347

**Comment by tcal-x** [comment]
Thanks @kgugala !

**Comment by tcal-x** [comment]
FYI @PiotrZierhoffer

**Comment by PiotrZierhoffer** [comment]
I believe this issue can be closed now?
