### ISSUE TITLE
Installing riscv64-unknown-elf-gcc from packages does not guarantee compilation

### ISSUE THREAD

**Issue by PiotrZierhoffer** [google/CFU-Playground#57]
The docs mention that the RISC-V toolchain has to be downloaded from [here](https://github.com/sifive/freedom-tools/releases/tag/v2020.04.0-Toolchain.Only).

The `scripts/setup` script tries to install it from apt.

This leads to a failure in compilation, complaining about missing cstdio.

In my opinion it would make sense to just point to relevant instructions in case the toolchain is missing.

**Comment by alanvgreen** [comment]
Hi Piotr: I think you're right!
